### ISSUE TITLE
Where's the reference you used in the video?

### ISSUE THREAD

**Issue by ghost** [b3agz/Code-A-Game-Like-Minecraft-In-Unity#16]
Can I have the reference please?

**Comment by PainOnRain** [comment]
For what?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 15 мар. 2021 г. в 12:03, cccreng ***@***.***>:
